// angular/src/app/footer/footer.component.ts

import { Component } from '@angular/core';


@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {
  date: number = new Date().getFullYear();
};
<footer>
    <div>Lukas Jönsson - Marcus Lennartsson</div>
    <div>© All rights reserved - Ius Reservari</div>
    <div>{{ date }}</div>
</footer>

// vue/src/components/Footer.vue
<template>
    <v-app>
        <v-footer class="bg-blue-darken-3 text-center d-flex flex-column" fixed>
            <div class="pt-0">Lukas Jönsson - Marcus Lennartsson</div>
            <div class="pt-0">© All rights reserved - Ius Reservari</div>
            <div>{{ new Date().getFullYear() }}</div>
        </v-footer>
    </v-app>
</template>

<style>
.v-application__wrap {
    bottom: 0 !important; 
    position: fixed !important; 
    padding-top: 0 !important; 
    width: 100% !important;
}
</style>
