// angular/src/app/input/input.component.ts

import { Component, Input, Output, EventEmitter } from '@angular/core';


@Component({
  selector: 'app-input',
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.css']
})
export class InputComponent {
  @Input() placeholder?: string = '';
  @Output() onHandleSearch = new EventEmitter<string>();

  handleSearch(event: any) {
    this.onHandleSearch.emit(event.target.value);
  };
};
<div>
  <mat-form-field>
    <mat-label>Search for {{ placeholder }}...</mat-label>
      <input matInput [placeholder]="'Search for ' + placeholder + '...'" (keyup.enter)="handleSearch($event)">
  </mat-form-field>
</div>

// vue/src/components/Input.vue
<script setup lang="ts">
defineProps({
  placeholder: String,
  data: Array,
  modelValue: String
});
defineEmits(['update:modelValue'])
</script>

<template>
    <v-text-field :label="`Search for ${placeholder}...`"  variant="underlined" :focused="false"
    @keyup.enter="$emit('update:modelValue', $event.target.value)">
    </v-text-field>
</template>
