// vue/src/views/Artist.vue
<script setup lang="ts">
import { useRoute } from 'vue-router';
import { onMounted, ref } from 'vue';
import axios from 'axios';
import Navbar from '../components/Navbar.vue';
import Footer from '../components/Footer.vue';


const route = useRoute();
let artist = ref<any[]>([]);

const fetchArtist = async () => {
  try {
    const response = await axios.get(`http://localhost:3001/api/v1/artists/${route.params.id}/setlists`, {
      params: {
        artistId: route.params.id
      }
    });
    artist.value = response.data.setlist;
  }
  catch (err) {
    console.error(err);
  };
};

const toggleShowSongs = (data:any) => {
  data.showSongs = !data.showSongs;
};

// equal to the 'useEffect' hook
onMounted(async () => {
  await fetchArtist();
});
</script>

<template>
  <Navbar />
    <main>
      <div v-if="artist.length > 0">
        <h1>{{ artist[0].artist.name }} setlists</h1>
          <v-list-item v-for="data in artist" :key="data.id">
              <v-table>
                <thead>
                  <tr>
                    <th @click="toggleShowSongs(data)"> {{ data.artist.name }} at {{ data.venue.name }} 
                      ({{ data.venue.city.name }}, {{ data.venue.city.country.name }})
                    </th>
                  </tr>
                </thead>
                  <tbody v-if="data.showSongs">
                    <tr v-for="(item, index) in data.sets.set[0].song" :key="item.name">
                      <td>{{ index + 1 }}. {{ item.name }}</td>
                    </tr>
                  </tbody>
              </v-table>
          </v-list-item>
      </div>
      <div v-else>
        <p>loading...</p>
      </div>
    </main>
  <Footer />
</template>

// react/src/views/Artist.tsx

import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
import NavBar from '../components/navbar';
import Footer from '../components/footer';
import useTitle from '../hooks/useTitle';


export default function Artist() {
  useTitle('Artist');

  const { mbid } = useParams();
  const [artist, setArtist] = useState<any[]>([]);

  const handleToggleSetlist = (data: any) => {
    data.showSetlist = !data.showSetlist;
    setArtist([...artist]);
  };

  useEffect(() => {
    const fetchArtist = async () => {
      try {
        const response = await axios.get(`http://localhost:3001/api/v1/artists/${mbid}/setlists`, {
          params: {
            artistId: mbid
          }
        });
        setArtist(response.data.setlist);
      } catch (err) {
        console.error(err);
      };
    };
    fetchArtist();
  }, [mbid]);

  return (
    <>
      <NavBar />
        <main>
            {artist.length > 0 && (
              <>
                <h2>{artist[0].artist.name}</h2>
                {artist.map((data) => (
                  <div key={data.id}>
                    <table>
                      <thead>
                        <tr onClick={() => handleToggleSetlist(data)}>
                          <th>
                            {data.artist.name} at {data.venue.name} ({data.venue.city.name}, {data.venue.city.country.name})
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {data.showSetlist && (
                          data?.sets?.set[0]?.song.map((item: any, index: number) => (
                            <tr key={item.name}>
                              <td>{index + 1}. {item.name}</td>
                            </tr>
                          ))
                        )}
                      </tbody>
                    </table>
                  </div>
                ))}
              </>
            )}
        </main>
      <Footer />
    </>
  );
};
