// vue/src/views/SetlistInCity.vue
<script setup lang="ts">
import { useRoute } from 'vue-router';
import { onMounted, ref } from 'vue';
import axios from 'axios';
import Navbar from '../components/Navbar.vue';
import Footer from '../components/Footer.vue';


const route = useRoute();
let setlists = ref<any[]>([]);

const fetchSetlistsInCity = async () => {
  try {
    const response = await axios.get(`http://localhost:3001/api/v1/search/cityId`, {
      params: {
        cityId: route.params.id
      }
    });
    setlists.value = response.data.setlist;
  }
  catch (err) {
    console.error(err);
  };
};

const toggleShowSongs = (data:any) => {
  data.showSongs = !data.showSongs;
};

onMounted(async () => {
    await fetchSetlistsInCity();
});
</script>

<template>
  <Navbar />
  <main>
    <h1>Setlists in city</h1>
    <div>
      <template v-if="setlists.length > 0">
        <v-list-item v-for="data in setlists" :key="data.id">
          <v-table>
            <thead>
              <tr>
                <th @click="toggleShowSongs(data)">
                  {{ data.artist.name }} at {{ data.venue.name }} ({{ data.venue.city.name }},
                  {{ data.venue.city.country.name }}) {{ data.eventDate }}
                </th>
              </tr>
            </thead>
            <tbody v-if="data.showSongs">
              <template v-if="data.sets.set[0] && data.sets.set[0].song">
                <tr v-for="(item, index) in data.sets.set[0].song" :key="item.name">
                  <td>{{ index + 1 }}. {{ item.name }}</td>
                </tr>
              </template>
              <template v-else>
                <tr>
                  <td>No songs available</td>
                </tr>
              </template>
            </tbody>
          </v-table>
        </v-list-item>
      </template>
      <p v-else>No songs</p>
    </div>
  </main>
  <Footer />
</template>

// react/src/views/SetlistInCity.tsx

import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
import NavBar from '../components/navbar';
import Footer from '../components/footer';
import useTitle from '../hooks/useTitle';


export default function SetlistInCity() {
  useTitle('City');

  const { id } = useParams();
  const [setlists, setSetlists] = useState<any[]>([]);

  useEffect(() => {
    const fetchSetlistsInCity = async () => {
        try {
            const response = await axios.get(`http://localhost:3001/api/v1/search/cityId`, {
            params: {
                cityId: id
            }
            });
            setSetlists(response.data.setlist);
        }
        catch (err) {
            console.error(err);
        };
      };
    fetchSetlistsInCity();
  }, [id]);

  const handleToggleSetlist = (data: any) => {
    data.showSetlist = !data.showSetlist;
    setSetlists([...setlists]);
  };

  return (
    <>
      <NavBar />
        <main>
        {setlists.length > 0 && (
            <>
            <h2>Setlists in { setlists[0].venue.city.name }</h2>
              {setlists.map((data) => (
                <div key={data.id}>
                  <table>
                    <thead>
                      <tr onClick={() => handleToggleSetlist(data)}>
                        <th>
                          {data.artist.name} at {data.venue.name} ({data.venue.city.name}, {data.venue.city.country.name})
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {data.showSetlist && (
                        data?.sets?.set[0]?.song.map((item: any, index: number) => (
                          <tr key={item.name}>
                            <td>{index + 1}. {item.name}</td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
            ))}
            </>
          )}
        </main>
      <Footer />
    </>
  );
};
